import "@/public/css/destyle.css"
import "@/public/css/global.scss"
import Header from "@/public/layouts/header"
import Footer from "@/public/layouts/footer"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" id="html">
      <body>
        <Header />
        <div className="l-inner">
          {children}
        </div>
        <Footer />
      </body>
    </html >
  )
}
