import Header from "@/public/layouts/header"
import Footer from "@/public/layouts/footer"
import "@/public/css/destyle.css"
import "@/public/css/global.scss"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
